spring:
  application:
    name: TestDemo

  datasource:
    username: sunjie
    password: 970306
    url: jdbc:mysql://47.106.8.7:3306/db_book?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000

  # 控制台高亮输出
  output:
    ansi:
      enabled: always

  redis:
    database: 0
    host: 47.106.8.7
    port: 6379
    password: 123456

    jedis:
      pool:
        max-active: 8
        max-wait: 2000m
        max-idle: 8
        min-idle: 0
    timeout: 2000m

server:
  port: 9090

