spring:
  application:
    name: TestDemo

  datasource:
    url: jdbc:mysql://47.106.8.7:3306/petshop?useUnicode=true&characterEncoding=utf-8&useSSL=true
    data-username: sunjie
    data-password: 970306
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 0
    host: 47.106.8.7
    port: 6379
    password: 123456

    jedis:
      pool:
        max-active: 8
        max-wait: 2000m
        max-idle: 8
        min-idle: 0
    timeout: 2000m

server:
  port: 9090

